POST http://localhost:8000/api/v1/auth/register 
Content-Type: application/json

{
"name": "admin", "email": "admin@mail.com", "password": "admin54321"
}

### login 
POST http://localhost:8000/api/v1/auth/login 
Content-Type: application/json

{
"email": "admin@mail.com", "password": "admin54321"
}

### Profile 
GET http://localhost:8000/api/v1/auth/profile 
Accept: application/json 
Authorization: Bearer 8|DFLvBooExIIHVmUnNNX5YZXASu8vF2wPjy0ZLIjN244777a1

### Logout 
POST http://localhost:8000/api/v1/auth/logout 
Accept: application/json 
Authorization: Bearer 8|DFLvBooExIIHVmUnNNX5YZXASu8vF2wPjy0ZLIjN244777a1