### Listar permisos 
GET http://127.0.0.1:8000/api/permiso 
Authorization: Bearer 9|SzVRNXGpqRNQw8g2J0nXTfdT4Cjbd6LPmYfFSsy9b686637c 
Accept: application/json

###

### Guardar permiso 
POST http://127.0.0.1:8000/api/permiso 
Authorization: Bearer 9|SzVRNXGpqRNQw8g2J0nXTfdT4Cjbd6LPmYfFSsy9b686637c 
Content-Type: application/json

{
"nombre": "CREAR_USUARIO", "detalle": "Permite registrar usuarios"
}

###

### Mostrar permiso 
GET http://127.0.0.1:8000/api/permiso/1 
Authorization: Bearer 9|SzVRNXGpqRNQw8g2J0nXTfdT4Cjbd6LPmYfFSsy9b686637c 
Accept: application/json

###

### Modificar permiso 
PUT http://127.0.0.1:8000/api/permiso/1 
Authorization: Bearer 9|SzVRNXGpqRNQw8g2J0nXTfdT4Cjbd6LPmYfFSsy9b686637c 
Content-Type: application/json

{
"nombre": "EDITAR_USUARIO", "detalle": "Permite editar usuarios"
}

###

### Eliminar permiso 
DELETE http://127.0.0.1:8000/api/permiso/1 
Authorization: Bearer 9|SzVRNXGpqRNQw8g2J0nXTfdT4Cjbd6LPmYfFSsy9b686637c 
Accept: application/json