GET http://127.0.0.1:8000/api/usuario 
Authorization: Bearer 9|SzVRNXGpqRNQw8g2J0nXTfdT4Cjbd6LPmYfFSsy9b686637c
Accept: application/json

### Guardar 
POST http://127.0.0.1:8000/api/usuario 
Authorization: Bearer 9|SzVRNXGpqRNQw8g2J0nXTfdT4Cjbd6LPmYfFSsy9b686637c
Content-Type: application/json

{
"name": "david", "email": "david@mail.com", "password": "david54321"
}

### mostrar 
GET http://127.0.0.1:8000/api/usuario/2 
Authorization: Bearer 9|SzVRNXGpqRNQw8g2J0nXTfdT4Cjbd6LPmYfFSsy9b686637c

### modificar 
PUT http://127.0.0.1:8000/api/usuario/2 
Authorization: Bearer 9|SzVRNXGpqRNQw8g2J0nXTfdT4Cjbd6LPmYfFSsy9b686637c
Content-Type: application/json

{
"name": "david", "email": "david@mail.com"
}

### eliminar 
DELETE http://127.0.0.1:8000/api/usuario/3 
Authorization: Bearer 9|SzVRNXGpqRNQw8g2J0nXTfdT4Cjbd6LPmYfFSsy9b686637c

### Asignar role 
POST http://127.0.0.1:8000/api/usuario/1/asignar_role 
Authorization: Bearer 9|SzVRNXGpqRNQw8g2J0nXTfdT4Cjbd6LPmYfFSsy9b686637c
Content-Type: application/json

{
"role": "ADMIN"
}

### quitar Role 
POST http://127.0.0.1:8000/api/usuario/1/quitar_role 
Authorization: Bearer 9|SzVRNXGpqRNQw8g2J0nXTfdT4Cjbd6LPmYfFSsy9b686637c
Content-Type: application/json

{
"role": "ADMIN"
}